import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Icon } from '@/components/Icon';
import { getServicesControlSettings, visibleServicesItems } from '@/lib/servicesControl';

export async function generateMetadata() { const control = await getServicesControlSettings(); const anyServiceVisible = visibleServicesItems(control.services).length > 0; return { title: anyServiceVisible ? 'Услуги Bullmet — производство металлоизделий' : 'Раздел временно скрыт | Bullmet', description: anyServiceVisible ? 'Производственные услуги Bullmet: лазерная резка, гибка металла, металлопрокат и изделия под заказ.' : 'Информационная страница о производственных направлениях Bullmet.', robots: anyServiceVisible ? { index: true, follow: true } : { index: false, follow: false } }; }

export default async function ServicesPage() {
  const control = await getServicesControlSettings();
  const services = visibleServicesItems(control.services); const steps = visibleServicesItems(control.steps); if (!control.hero.enabled || !services.length) notFound();
  return <><Header /><main className="services-page-v2"><section className="services-hero-v2"><div className="services-hero-copy-v2"><nav className="services-breadcrumbs-v2" aria-label="Хлебные крошки"><Link href="/">Главная</Link><span>›</span><span>Услуги</span></nav><p className="page-kicker">{control.hero.kicker}</p><h1>{control.hero.title}</h1><p>{control.hero.text}</p><div className="services-hero-actions-v2"><Link href="/contacts">{control.hero.primaryLabel}</Link><Link href="/catalog">{control.hero.secondaryLabel}</Link></div></div><div className="services-hero-media-v2"><Image src={control.hero.image} alt="Производство Bullmet" width={900} height={560} priority /><div><b>Собственное производство</b><span>металл, дерево и изделия под задачу</span></div></div></section><section className="services-quick-v2" aria-label="Основные услуги">{services.map((service) => <Link href={`#${service.id}`} key={service.id}><Icon name={service.icon as any} /><span>{service.title}</span></Link>)}</section><section className="services-list-v2"><div className="services-section-head-v2"><p className="page-kicker">Производственные направления</p><h2>Что умеет производство Bullmet</h2><span>Посмотрите направления производства и свяжитесь с нами, если нужна консультация по изделию.</span></div><div className="services-grid-v2">{services.map((service) => <article id={service.id} key={service.id}><div className="service-image-v2"><Image src={service.image} alt={service.title} width={620} height={410} /></div><div className="service-body-v2"><Icon name={service.icon as any} /><h3>{service.title}</h3><p>{service.subtitle}</p><ul>{service.items.map((item) => <li key={item}>{item}</li>)}</ul><Link href={service.href}>Подробнее</Link></div></article>)}</div></section><section className="services-examples-v2"><div><p className="page-kicker">Возможные задачи</p><h2>Какие изделия можно делать</h2><p>Эти примеры можно использовать как направления для будущего развития услуг и контента.</p></div><div className="services-example-tags-v2">{control.examples.map((example) => <span key={example}>{example}</span>)}</div></section><section className="services-process-v2"><div className="services-section-head-v2"><p className="page-kicker">Процесс</p><h2>Как обычно проходит работа</h2></div><div className="services-process-grid-v2">{steps.map((step) => <article key={step.id}><b>{step.number}</b><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section></main><Footer /></>;
}
