import Image from 'next/image';
import Link from 'next/link';
import { Box, CheckCircle2, Clock3, Layers3, Paintbrush, ShieldCheck, ShoppingBag, Wrench } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { getProductionControlSettings, visibleProductionItems, type ProductionFact, type ProductionPoint } from '@/lib/productionControl';

export const metadata = { title: 'Производство Bullmet — настенные часы из металла и дерева', description: 'Как создаются настенные часы Bullmet: металл, дерево, резка, обработка, покраска, сборка и контроль качества.' };

const factIcons = { shield: ShieldCheck, layers: Layers3, check: CheckCircle2 };
const pointIcons = { layers: Layers3, paint: Paintbrush, box: Box, clock: Clock3, tools: Wrench };

function ClockPoint({ item, side }: { item: ProductionPoint; side: 'left' | 'right' }) { const Icon = pointIcons[item.icon]; return <article className={`production-clock-point production-clock-point--${side}`}><Icon aria-hidden="true" /><div><h3>{item.title}</h3><p>{item.text}</p></div></article>; }

export default async function ProductionPage() {
  const settings = await getProductionControlSettings(); const facts = visibleProductionItems(settings.facts); const left = visibleProductionItems(settings.structure.left); const right = visibleProductionItems(settings.structure.right); const steps = visibleProductionItems(settings.process.steps); const results = visibleProductionItems(settings.results.items);
  return <><Header /><main className="production-story-page">
    {settings.hero.enabled && <section className="production-story-hero"><div className="production-story-hero-copy"><nav className="production-story-breadcrumbs" aria-label="Хлебные крошки"><Link href="/">Главная</Link><span>›</span><span>Производство</span></nav><p className="production-story-kicker">{settings.hero.kicker}</p><h1>{settings.hero.title}</h1><p className="production-story-lead">{settings.hero.text}</p><div className="production-story-actions"><Link className="production-story-button production-story-button--accent" href="/catalog">{settings.hero.catalogLabel}</Link><Link className="production-story-button production-story-button--light" href="/contacts">{settings.hero.contactLabel}</Link></div></div><div className="production-story-hero-media"><Image src={settings.hero.image} alt="Лазерная резка на производстве Bullmet" fill priority sizes="(max-width: 767px) 100vw, 57vw" /></div><div className="production-story-facts">{facts.map((item: ProductionFact) => { const Icon = factIcons[item.icon]; return <article key={item.id}><Icon aria-hidden="true" /><div><h2>{item.title}</h2><p>{item.text}</p></div></article>; })}</div></section>}
    {settings.structure.enabled && <section className="production-clock-structure"><div className="production-story-section-head"><p className="production-story-kicker">{settings.structure.eyebrow}</p><h2>{settings.structure.title}</h2></div><div className="production-clock-diagram"><div className="production-clock-points production-clock-points--left">{left.map((item) => <ClockPoint item={item} side="left" key={item.id} />)}</div><div className="production-clock-image"><Image src={settings.structure.image} alt={settings.structure.imageAlt} fill sizes="(max-width: 767px) 80vw, 500px" /></div><div className="production-clock-points production-clock-points--right">{right.map((item) => <ClockPoint item={item} side="right" key={item.id} />)}</div></div></section>}
    {settings.process.enabled && <section className="production-process-dark"><div className="production-process-head"><h2>{settings.process.title}</h2></div><div className="production-process-timeline">{steps.map((step) => <article className="production-process-step" key={step.id}><span>{step.number}</span><h3>{step.title}</h3><div className="production-process-step-image"><Image src={step.image} alt="" fill sizes="(max-width: 767px) 100vw, 16vw" /></div><p>{step.text}</p></article>)}</div></section>}
    {settings.results.enabled && <section className="production-result-section"><div className="production-story-section-head"><h2>{settings.results.title}</h2><p>{settings.results.text}</p></div><div className="production-result-grid">{results.map((item) => <article className="production-result-card" key={item.id}><div><Image src={item.image} alt={item.title} fill sizes="(max-width: 767px) 100vw, 21vw" /></div><h3>{item.title}</h3><p>{item.text}</p></article>)}<aside className="production-result-cta"><ShoppingBag aria-hidden="true" /><h2>{settings.results.ctaTitle}</h2><p>{settings.results.ctaText}</p><Link className="production-story-button production-story-button--accent" href="/catalog">{settings.results.ctaLabel}</Link></aside></div></section>}
    <section className="production-brand-strip"><div className="production-brand-intro"><ShieldCheck aria-hidden="true" /><p><strong>Bullmet</strong> — это сочетание металла, дерева и внимательного отношения к деталям.</p></div><div className="production-brand-features"><span><Layers3 aria-hidden="true" />Качественные материалы</span><span><Wrench aria-hidden="true" />Современное оборудование</span><span><Paintbrush aria-hidden="true" />Аккуратная сборка</span><span><CheckCircle2 aria-hidden="true" />Контроль качества</span></div></section>
  </main><Footer /></>;
}
