'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Eye, EyeOff, Save } from 'lucide-react';
import { AdminImagePicker } from '@/components/AdminImagePicker';
import type { ProductionControlSettings, ProductionFact, ProductionPoint, ProductionResult, ProductionStep } from '@/lib/productionControl';

function Field({ label, value, change, area = false }: { label: string; value: string; change: (value: string) => void; area?: boolean }) {
  return <label className="admin-production-field"><span>{label}</span>{area ? <textarea rows={3} value={value} onChange={(event) => change(event.target.value)} /> : <input value={value} onChange={(event) => change(event.target.value)} />}</label>;
}
function Toggle({ value, change }: { value: boolean; change: () => void }) { return <button type="button" className={value ? 'admin-production-toggle is-on' : 'admin-production-toggle'} onClick={change}>{value ? <Eye size={16} /> : <EyeOff size={16} />}{value ? 'Опубликовано' : 'Скрыто'}</button>; }
function changeItem<T extends { id: string }>(items: T[], id: string, patch: Partial<T>) { return items.map((item) => item.id === id ? { ...item, ...patch } : item); }

export function AdminProductionClient({ initialSettings }: { initialSettings: ProductionControlSettings }) {
  const [settings, setSettings] = useState(initialSettings); const [tab, setTab] = useState<'hero' | 'structure' | 'process' | 'result'>('hero'); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const patch = <K extends keyof ProductionControlSettings>(section: K, value: Partial<ProductionControlSettings[K]>) => setSettings((current) => ({ ...current, [section]: { ...current[section], ...value } }));
  async function save() { setSaving(true); setMessage(''); try { const response = await fetch('/api/admin/production-control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Не удалось сохранить производство.'); setSettings(data.settings || settings); setMessage('Страница производства сохранена и обновлена на сайте.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Ошибка сохранения.'); } finally { setSaving(false); } }
  const ItemToggle = ({ item, onChange }: { item: { visible: boolean }; onChange: () => void }) => <Toggle value={item.visible} change={onChange} />;
  return <div className="admin-production-editor">
    <section className="admin-production-hero"><div><p>Контент сайта</p><h1>Производство</h1><span>Самостоятельно редактируйте каждый смысловой блок страницы: тексты, изображения, порядок и публикацию.</span></div><div><Link href="/production" target="_blank">Открыть страницу ↗</Link><button type="button" onClick={save} disabled={saving}><Save size={17} />{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></section>
    {message && <p className="admin-production-message">{message}</p>}
    <nav className="admin-production-tabs"><button onClick={() => setTab('hero')} className={tab === 'hero' ? 'active' : ''}>Первый экран</button><button onClick={() => setTab('structure')} className={tab === 'structure' ? 'active' : ''}>Состав часов</button><button onClick={() => setTab('process')} className={tab === 'process' ? 'active' : ''}>Процесс</button><button onClick={() => setTab('result')} className={tab === 'result' ? 'active' : ''}>Результаты</button></nav>
    {tab === 'hero' && <section className="admin-production-card"><header><div><h2>Первый экран</h2><span>Главная история производства и карточки доверия.</span></div><Toggle value={settings.hero.enabled} change={() => patch('hero', { enabled: !settings.hero.enabled })} /></header><div className="admin-production-grid"><Field label="Надзаголовок" value={settings.hero.kicker} change={(kicker) => patch('hero', { kicker })} /><Field label="Заголовок" value={settings.hero.title} change={(title) => patch('hero', { title })} /><Field label="Текст" value={settings.hero.text} change={(text) => patch('hero', { text })} area /><AdminImagePicker label="Фото первого экрана" value={settings.hero.image} onChange={(image) => patch('hero', { image })} /><Field label="Кнопка каталога" value={settings.hero.catalogLabel} change={(catalogLabel) => patch('hero', { catalogLabel })} /><Field label="Кнопка связи" value={settings.hero.contactLabel} change={(contactLabel) => patch('hero', { contactLabel })} /></div><h3>Карточки доверия</h3><div className="admin-production-list">{settings.facts.map((item) => <article key={item.id}><ItemToggle item={item} onChange={() => setSettings((current) => ({ ...current, facts: changeItem(current.facts, item.id, { visible: !item.visible }) }))} /><Field label="Заголовок" value={item.title} change={(title) => setSettings((current) => ({ ...current, facts: changeItem(current.facts, item.id, { title }) }))} /><Field label="Описание" value={item.text} change={(text) => setSettings((current) => ({ ...current, facts: changeItem(current.facts, item.id, { text }) }))} /><label>Порядок<input type="number" value={item.order} onChange={(event) => setSettings((current) => ({ ...current, facts: changeItem(current.facts, item.id, { order: Number(event.target.value) || item.order }) }))} /></label></article>)}</div></section>}
    {tab === 'structure' && <section className="admin-production-card"><header><div><h2>Состав часов</h2><span>Изображение и пояснения вокруг него.</span></div><Toggle value={settings.structure.enabled} change={() => patch('structure', { enabled: !settings.structure.enabled })} /></header><div className="admin-production-grid"><Field label="Надзаголовок" value={settings.structure.eyebrow} change={(eyebrow) => patch('structure', { eyebrow })} /><Field label="Заголовок" value={settings.structure.title} change={(title) => patch('structure', { title })} /><AdminImagePicker label="Изображение часов" value={settings.structure.image} onChange={(image) => patch('structure', { image })} altValue={settings.structure.imageAlt} onAltChange={(imageAlt) => patch('structure', { imageAlt })} /></div><div className="admin-production-two-columns">{(['left', 'right'] as const).map((side) => <div key={side}><h3>{side === 'left' ? 'Слева от изображения' : 'Справа от изображения'}</h3><div className="admin-production-list">{settings.structure[side].map((item) => <article key={item.id}><ItemToggle item={item} onChange={() => setSettings((current) => ({ ...current, structure: { ...current.structure, [side]: changeItem(current.structure[side], item.id, { visible: !item.visible }) } }))} /><Field label="Заголовок" value={item.title} change={(title) => setSettings((current) => ({ ...current, structure: { ...current.structure, [side]: changeItem(current.structure[side], item.id, { title }) } }))} /><Field label="Описание" value={item.text} change={(text) => setSettings((current) => ({ ...current, structure: { ...current.structure, [side]: changeItem(current.structure[side], item.id, { text }) } }))} /></article>)}</div></div>)}</div></section>}
    {tab === 'process' && <section className="admin-production-card"><header><div><h2>Этапы производства</h2><span>Порядок, тексты и фото процесса.</span></div><Toggle value={settings.process.enabled} change={() => patch('process', { enabled: !settings.process.enabled })} /></header><Field label="Заголовок блока" value={settings.process.title} change={(title) => patch('process', { title })} /><div className="admin-production-steps">{settings.process.steps.map((item) => <article key={item.id}><ItemToggle item={item} onChange={() => setSettings((current) => ({ ...current, process: { ...current.process, steps: changeItem(current.process.steps, item.id, { visible: !item.visible }) } }))} /><Field label="Номер" value={item.number} change={(number) => setSettings((current) => ({ ...current, process: { ...current.process, steps: changeItem(current.process.steps, item.id, { number }) } }))} /><Field label="Название" value={item.title} change={(title) => setSettings((current) => ({ ...current, process: { ...current.process, steps: changeItem(current.process.steps, item.id, { title }) } }))} /><Field label="Описание" value={item.text} change={(text) => setSettings((current) => ({ ...current, process: { ...current.process, steps: changeItem(current.process.steps, item.id, { text }) } }))} area /><AdminImagePicker label="Фото этапа" value={item.image} onChange={(image) => setSettings((current) => ({ ...current, process: { ...current.process, steps: changeItem(current.process.steps, item.id, { image }) } }))} /></article>)}</div></section>}
    {tab === 'result' && <section className="admin-production-card"><header><div><h2>Готовый результат</h2><span>Карточки применения и финальный призыв к действию.</span></div><Toggle value={settings.results.enabled} change={() => patch('results', { enabled: !settings.results.enabled })} /></header><div className="admin-production-grid"><Field label="Заголовок" value={settings.results.title} change={(title) => patch('results', { title })} /><Field label="Описание" value={settings.results.text} change={(text) => patch('results', { text })} /><Field label="Заголовок CTA" value={settings.results.ctaTitle} change={(ctaTitle) => patch('results', { ctaTitle })} /><Field label="Текст CTA" value={settings.results.ctaText} change={(ctaText) => patch('results', { ctaText })} /><Field label="Кнопка CTA" value={settings.results.ctaLabel} change={(ctaLabel) => patch('results', { ctaLabel })} /></div><div className="admin-production-results">{settings.results.items.map((item) => <article key={item.id}><ItemToggle item={item} onChange={() => setSettings((current) => ({ ...current, results: { ...current.results, items: changeItem(current.results.items, item.id, { visible: !item.visible }) } }))} /><Field label="Заголовок" value={item.title} change={(title) => setSettings((current) => ({ ...current, results: { ...current.results, items: changeItem(current.results.items, item.id, { title }) } }))} /><Field label="Описание" value={item.text} change={(text) => setSettings((current) => ({ ...current, results: { ...current.results, items: changeItem(current.results.items, item.id, { text }) } }))} /><AdminImagePicker label="Фото" value={item.image} onChange={(image) => setSettings((current) => ({ ...current, results: { ...current.results, items: changeItem(current.results.items, item.id, { image }) } }))} /></article>)}</div></section>}
  </div>;
}
