'use client';

import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { ArrowLeft, ChevronDown, Download, FileDown, FileJson, FileSpreadsheet, Filter, Package, Percent, Plus, Save, Search, ShoppingBag, SlidersHorizontal, Star, Truck, Users, WalletCards, X } from 'lucide-react';
import type { AdminOrder } from '@/lib/adminCommerce';
import type { CatalogProduct } from '@/lib/products';
import type { AdminReview } from '@/lib/adminContent';
import type { AdminCoupon, CouponUsage } from '@/lib/adminCoupons';
import type { AdminProfile } from '@/lib/adminPeople';

type ReportType = 'sales'|'orders'|'products'|'categories'|'customers'|'coupons'|'delivery'|'payment'|'reviews'|'full';
type Period = 'today'|'7'|'30'|'month'|'previousMonth'|'custom';
type Field = { key:string; label:string };
type Template = { id:string; name:string; type:ReportType; period:Period; status:string[]; columns:string[]; createdAt:string };
type History = { id:string; name:string; type:ReportType; format:'XLSX'|'CSV'|'JSON'; rows:number; createdAt:string; period:Period };
type Props = { orders:AdminOrder[]; products:CatalogProduct[]; reviews:AdminReview[]; coupons:AdminCoupon[]; usages:CouponUsage[]; profiles:AdminProfile[] };
const fields = (items: Array<[string,string]>): Field[] => items.map(([key,label])=>({key,label}));

const reportDefinitions: Record<ReportType, { title:string; description:string; icon:any; fields:Field[] }> = {
  sales:{ title:'Продажи', description:'Выручка, товары, скидки и детали заказов.', icon:ShoppingBag, fields:fields([['date','Дата'],['order','№ заказа'],['customer','Покупатель'],['items','Товары'],['quantity','Количество'],['amount','Сумма товаров'],['discount','Скидка'],['delivery','Доставка'],['total','Итого'],['status','Статус']]) },
  orders:{ title:'Заказы', description:'Статусы, оплата, доставка и менеджеры.', icon:FileSpreadsheet, fields:fields([['order','№ заказа'],['date','Дата'],['customer','Покупатель'],['phone','Телефон'],['email','Email'],['status','Статус'],['payment','Способ оплаты'],['delivery','Способ получения'],['total','Сумма'],['manager','Менеджер'],['source','Источник']]) },
  products:{ title:'Товары', description:'Продажи, количество и выручка по товарам.', icon:Package, fields:fields([['title','Товар'],['sku','Артикул'],['category','Категория'],['sold','Продано штук'],['orders','Количество заказов'],['revenue','Выручка'],['average','Средняя цена продажи'],['lastSale','Последняя продажа']]) },
  categories:{ title:'Категории', description:'Продажи и выручка по категориям каталога.', icon:SlidersHorizontal, fields:fields([['category','Категория'],['sold','Продано товаров'],['orders','Количество заказов'],['revenue','Выручка'],['average','Средний чек'],['share','Доля в общей выручке']]) },
  customers:{ title:'Покупатели', description:'Активность клиентов и история покупок.', icon:Users, fields:fields([['name','Имя'],['phone','Телефон'],['email','Email'],['orders','Количество заказов'],['total','Общая сумма покупок'],['average','Средний чек'],['first','Первый заказ'],['last','Последний заказ'],['status','Статус клиента']]) },
  coupons:{ title:'Купоны и скидки', description:'Использование промокодов и сумма скидок.', icon:Percent, fields:fields([['name','Купон'],['code','Промокод'],['uses','Использований'],['customers','Уникальных покупателей'],['amount','Сумма заказов'],['discount','Сумма скидок'],['average','Средняя скидка'],['period','Период действия']]) },
  delivery:{ title:'Доставка', description:'Способы получения, стоимость и количество заказов.', icon:Truck, fields:fields([['delivery','Способ получения'],['orders','Количество заказов'],['amount','Сумма заказов'],['average','Средний заказ'],['cost','Стоимость доставки'],['share','Доля заказов']]) },
  payment:{ title:'Оплата', description:'Способы оплаты, статусы и суммы платежей.', icon:WalletCards, fields:fields([['order','Заказ'],['customer','Покупатель'],['payment','Способ оплаты'],['status','Статус оплаты'],['amount','Сумма'],['date','Дата оплаты']]) },
  reviews:{ title:'Отзывы', description:'Оценки, товары и активность покупателей.', icon:Star, fields:fields([['date','Дата'],['customer','Покупатель'],['product','Товар'],['rating','Оценка'],['text','Текст'],['status','Статус'],['photos','Есть фото'],['source','Источник']]) },
  full:{ title:'Полный отчёт', description:'Объединённая сводка по основным данным магазина.', icon:FileJson, fields:[{key:'section',label:'Раздел'},{key:'title',label:'Показатель'},{key:'value',label:'Значение'}] }
};
const defaults: Record<ReportType,string[]> = Object.fromEntries(Object.entries(reportDefinitions).map(([key,value])=>[key,value.fields.slice(0,10).map((field)=>field.key)])) as Record<ReportType,string[]>;
const storeKey = 'bullmet-report-templates-v1'; const historyKey = 'bullmet-report-history-v1'; const money = (value:any) => `${new Intl.NumberFormat('ru-RU').format(Number(value || 0))} BYN`; const rawDate = (value?:string) => value ? new Date(value).toLocaleDateString('ru-RU') : '—';
const paidStatuses = new Set(['Оплачен','Передан в доставку','Выполнен']);

function rangeFor(period:Period, from:string, to:string) { const end = to ? new Date(`${to}T23:59:59`) : new Date(); const start = from ? new Date(`${from}T00:00:00`) : new Date(end); if (!from) { if(period==='today') start.setHours(0,0,0,0); if(period==='7') start.setDate(start.getDate()-6); if(period==='30') start.setDate(start.getDate()-29); if(period==='month') start.setDate(1); if(period==='previousMonth') { start.setDate(1); start.setMonth(start.getMonth()-1); end.setDate(0); end.setHours(23,59,59,999); } } return { start,end }; }
function dateInRange(value:string|undefined, range:{start:Date;end:Date}) { const date = value ? new Date(value) : null; return Boolean(date && date >= range.start && date <= range.end); }
function download(name:string, text:string, mime:string) { const url=URL.createObjectURL(new Blob([text],{type:mime})); const link=document.createElement('a'); link.href=url; link.download=name; link.click(); URL.revokeObjectURL(url); }
function csv(rows:Record<string,any>[], columns:Field[]) { const esc=(value:any)=>`"${String(value ?? '').replace(/"/g,'""')}"`; return '\ufeff'+[columns.map((field)=>esc(field.label)).join(','),...rows.map((row)=>columns.map((field)=>esc(row[field.key])).join(','))].join('\n'); }

export function AdminReportsClient({ orders, products, reviews, coupons, usages, profiles }:Props) {
  const [type,setType]=useState<ReportType>('sales'); const [period,setPeriod]=useState<Period>('30'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [status,setStatus]=useState<string[]>(['Оплачен','Передан в доставку','Выполнен']); const [category,setCategory]=useState(''); const [payment,setPayment]=useState(''); const [delivery,setDelivery]=useState(''); const [search,setSearch]=useState(''); const [columns,setColumns]=useState<string[]>(defaults.sales); const [page,setPage]=useState(1); const [perPage,setPerPage]=useState(5); const [showColumns,setShowColumns]=useState(false); const [showCreate,setShowCreate]=useState(false); const [showTemplate,setShowTemplate]=useState(false); const [templateName,setTemplateName]=useState(''); const [templates,setTemplates]=useState<Template[]>([]); const [history,setHistory]=useState<History[]>([]); const [exporting,setExporting]=useState(false);
  useEffect(()=>{ try { setTemplates(JSON.parse(localStorage.getItem(storeKey)||'[]')); setHistory(JSON.parse(localStorage.getItem(historyKey)||'[]')); } catch {} },[]);
  useEffect(()=>{ setColumns(defaults[type]); setPage(1); setSearch(''); if(type==='sales') setStatus(['Оплачен','Передан в доставку','Выполнен']); else setStatus([]); },[type]);
  const definition=reportDefinitions[type]; const DefinitionIcon=definition.icon; const range=useMemo(()=>rangeFor(period,from,to),[period,from,to]); const categories=useMemo(()=>Array.from(new Set(products.map((product)=>product.category).filter(Boolean))) as string[],[products]); const productMap=useMemo(()=>new Map(products.map((product)=>[product.slug,product])),[products]); const payments=useMemo(()=>Array.from(new Set(orders.map((order)=>order.payment_method).filter(Boolean))) as string[],[orders]); const deliveries=useMemo(()=>Array.from(new Set(orders.map((order)=>order.delivery).filter(Boolean))) as string[],[orders]);
  const filteredOrders=useMemo(()=>orders.filter((order)=>dateInRange(order.created_at,range)).filter((order)=>!status.length || status.includes(order.status||'Новый')).filter((order)=>!payment || order.payment_method===payment).filter((order)=>!delivery || order.delivery===delivery).filter((order)=>!category || (order.items||[]).some((item)=>productMap.get(item.slug||'')?.category===category)),[orders,range,status,payment,delivery,category,productMap]);
  const dataset=useMemo(()=>buildRows(type,filteredOrders,products,reviews,coupons,usages,productMap,range),[type,filteredOrders,products,reviews,coupons,usages,productMap,range]);
  const activeFields=definition.fields.filter((field)=>columns.includes(field.key)); const searched=dataset.filter((row)=>Object.values(row).some((value)=>String(value||'').toLowerCase().includes(search.toLowerCase()))); const totalPages=Math.max(1,Math.ceil(searched.length/perPage)); const preview=searched.slice((page-1)*perPage,page*perPage); const activeFilters=Boolean(status.length||category||payment||delivery);
  function selectType(next:ReportType) { setType(next); document.getElementById('report-workspace')?.scrollIntoView({behavior:'smooth',block:'start'}); }
  function resetFilters(){ setStatus(type==='sales'?['Оплачен','Передан в доставку','Выполнен']:[]);setCategory('');setPayment('');setDelivery('');setSearch('');setPage(1); }
  function addHistory(format:History['format']) { const item={id:crypto.randomUUID(),name:definition.title,type,format,rows:searched.length,createdAt:new Date().toISOString(),period}; const next=[item,...history].slice(0,20); setHistory(next); localStorage.setItem(historyKey,JSON.stringify(next)); }
  function exportReport(format:History['format']) { setExporting(true); try { const rows=searched.map((row)=>Object.fromEntries(activeFields.map((field)=>[field.label,row[field.key] ?? '']))); const file=`bullmet-${type}-${new Date().toISOString().slice(0,10)}`; if(format==='CSV') download(`${file}.csv`,csv(searched,activeFields),'text/csv;charset=utf-8'); if(format==='JSON') download(`${file}.json`,JSON.stringify(rows,null,2),'application/json;charset=utf-8'); if(format==='XLSX') { const sheet=XLSX.utils.json_to_sheet(rows); sheet['!freeze']={xSplit:0,ySplit:1}; sheet['!cols']=activeFields.map((field)=>({ wch:Math.min(38,Math.max(14,field.label.length+7)) })); const book=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,sheet,definition.title.slice(0,31)); XLSX.writeFile(book,`${file}.xlsx`); } addHistory(format); } catch { window.alert('Не удалось сформировать отчёт. Повторите попытку.'); } finally { setExporting(false); } }
  function saveTemplate(){ const name=templateName.trim(); if(!name) return; const item={id:crypto.randomUUID(),name,type,period,status,columns,createdAt:new Date().toISOString()}; const next=[item,...templates]; setTemplates(next);localStorage.setItem(storeKey,JSON.stringify(next));setTemplateName('');setShowTemplate(false); }
  function runTemplate(template:Template){ setType(template.type);setPeriod(template.period);setStatus(template.status);setColumns(template.columns); document.getElementById('report-workspace')?.scrollIntoView({behavior:'smooth'}); }
  return <div className="admin-reports-v2">
    <header className="admin-reports-v2-head"><div><h1>Отчёты</h1><p>Формируйте и выгружайте данные магазина. Используйте готовые шаблоны или создавайте собственные отчёты.</p></div><div><button onClick={()=>setShowCreate(true)} className="primary"><Plus size={17}/>Создать отчёт</button><button aria-label="Дополнительные действия">•••</button></div></header>
    <div className="admin-reports-v2-layout"><section><article className="admin-reports-v2-card"><header><h2>Готовые отчёты</h2><span>Выберите нужный отчёт и настройте период и фильтры.</span></header><div className="admin-report-templates-v2">{(Object.keys(reportDefinitions) as ReportType[]).map((key)=>{const item=reportDefinitions[key],Icon=item.icon;return <article key={key} className={type===key?'selected':''}><Icon size={22}/><b>{item.title}</b><p>{item.description}</p><button onClick={()=>selectType(key)}>Сформировать <ChevronDown size={15}/></button></article>;})}</div></article>
      <section id="report-workspace" className="admin-reports-work-v2"><header><button className="back" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><ArrowLeft size={17}/></button><span><i><DefinitionIcon size={19}/></i><b>Отчёт: {definition.title}</b><small>{definition.description}</small></span><button onClick={()=>setShowTemplate(true)}><Save size={15}/>Сохранить как шаблон</button></header><div className="admin-reports-period-v2">{([['today','Сегодня'],['7','7 дней'],['30','30 дней'],['month','Этот месяц'],['previousMonth','Прошлый месяц'],['custom','Свой период']] as [Period,string][]).map(([key,label])=><button key={key} className={period===key?'active':''} onClick={()=>setPeriod(key)}>{label}</button>)}{period==='custom'&&<><input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/><span>—</span><input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/></>}</div>
        <div className="admin-reports-filters-v2"><label>Статусы заказов<select multiple value={status} onChange={(event)=>setStatus(Array.from(event.target.selectedOptions).map((option)=>option.value))}>{['Новый','В работе','Ожидает оплаты','Оплачен','Передан в доставку','Выполнен','Отменён'].map((item)=><option key={item}>{item}</option>)}</select></label><label>Категория<select value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">Все категории</option>{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label>Способ оплаты<select value={payment} onChange={(event)=>setPayment(event.target.value)}><option value="">Все способы</option>{payments.map((item)=><option key={item}>{item}</option>)}</select></label><label>Доставка<select value={delivery} onChange={(event)=>setDelivery(event.target.value)}><option value="">Все способы</option>{deliveries.map((item)=><option key={item}>{item}</option>)}</select></label>{activeFilters&&<button className="reset" onClick={resetFilters}>Сбросить</button>}</div>
        <article className="admin-preview-v2"><header><div><h2>Предпросмотр данных</h2><p>Показаны первые строки. В выгрузке будут все данные по выбранным фильтрам.</p></div><span>Найдено: <b>{searched.length}</b> строк · <b>{filteredOrders.reduce((sum,order)=>sum+(order.items||[]).reduce((total,item)=>total+Number(item.quantity||1),0),0)}</b> товаров · <b>{money(filteredOrders.filter((order)=>paidStatuses.has(order.status||'')).reduce((sum,order)=>sum+Number(order.total||0),0))}</b></span></header><div className="admin-preview-controls-v2"><label><Search size={15}/><input value={search} onChange={(event)=>{setSearch(event.target.value);setPage(1);}} placeholder="Поиск в отчёте..."/></label><button onClick={()=>setShowColumns(!showColumns)}><SlidersHorizontal size={15}/>Колонки</button></div>{showColumns&&<div className="admin-report-columns-v2">{definition.fields.map((field)=><label key={field.key}><input type="checkbox" checked={columns.includes(field.key)} onChange={()=>setColumns((current)=>current.includes(field.key)?current.filter((key)=>key!==field.key):[...current,field.key])}/>{field.label}</label>)}</div>} {preview.length ? <><div className="admin-preview-table-v2"><table><thead><tr>{activeFields.map((field)=><th key={field.key}>{field.label}</th>)}</tr></thead><tbody>{preview.map((row,index)=><tr key={row.id||index}>{activeFields.map((field)=><td key={field.key}>{row[field.key] ?? '—'}</td>)}</tr>)}</tbody></table></div><footer><span>Показано {Math.min((page-1)*perPage+1,searched.length)}–{Math.min(page*perPage,searched.length)} из {searched.length}</span><label>Строк <select value={perPage} onChange={(event)=>{setPerPage(Number(event.target.value));setPage(1)}}><option value="5">5</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label><button disabled={page===1} onClick={()=>setPage(page-1)}>‹</button><b>{page}/{totalPages}</b><button disabled={page===totalPages} onClick={()=>setPage(page+1)}>›</button></footer></> : <div className="admin-report-empty-v2">Данных за выбранный период нет.<button onClick={resetFilters}>Сбросить фильтры</button></div>}</article><footer className="admin-export-v2"><button disabled={exporting||!searched.length} onClick={()=>exportReport('XLSX')} className="primary"><FileSpreadsheet size={16}/>{exporting?'Формирование…':'Скачать XLSX'}</button><button disabled={exporting||!searched.length} onClick={()=>exportReport('CSV')}><FileDown size={16}/>CSV</button><button disabled={exporting||!searched.length} onClick={()=>exportReport('JSON')}><FileJson size={16}/>JSON</button></footer></section>
    </section><aside className="admin-reports-side-v2"><ReportSide title="Сохранённые шаблоны" action="Все шаблоны" empty="Сохранённых шаблонов пока нет.">{templates.slice(0,5).map((item)=><button key={item.id} onClick={()=>runTemplate(item)}><i><Save size={15}/></i><span><b>{item.name}</b><small>{reportDefinitions[item.type].title} · {item.period==='previousMonth'?'прошлый месяц':periodLabel(item.period)}</small></span><ChevronDown size={15}/></button>)}</ReportSide><ReportSide title="Последние отчёты" action="Все отчёты" empty="Вы ещё не формировали отчёты.">{history.slice(0,5).map((item)=><button key={item.id} onClick={()=>{setType(item.type);setPeriod(item.period)}}><i><Download size={15}/></i><span><b>{reportDefinitions[item.type].title} — {rawDate(item.createdAt)}</b><small>{rawDate(item.createdAt)} · {item.format} · {item.rows} строк</small></span><Download size={15}/></button>)}</ReportSide><article className="admin-report-help-v2"><Filter size={22}/><h3>Нужен другой отчёт?</h3><p>Создайте собственный отчёт с нужными полями и фильтрами.</p><button onClick={()=>setShowCreate(true)}><Plus size={16}/>Создать отчёт</button></article></aside></div>
    {(showCreate||showTemplate)&&<div className="admin-report-modal-v2" role="dialog" aria-modal="true"><article><button className="close" onClick={()=>{setShowCreate(false);setShowTemplate(false)}}><X size={18}/></button><h2>{showTemplate?'Сохранить как шаблон':'Создать отчёт'}</h2>{showTemplate?<><p>Шаблон сохранит тип отчёта, период, фильтры и выбранные колонки.</p><input autoFocus value={templateName} onChange={(event)=>setTemplateName(event.target.value)} placeholder="Название шаблона*"/><button className="primary" onClick={saveTemplate}>Сохранить шаблон</button></>:<><p>Выберите, какие данные вы хотите получить. Поля и фильтры можно настроить на следующем шаге.</p><div>{(Object.keys(reportDefinitions) as ReportType[]).filter((key)=>key!=='full').map((key)=>{const Icon=reportDefinitions[key].icon; return <button key={key} onClick={()=>{setType(key);setShowCreate(false);document.getElementById('report-workspace')?.scrollIntoView({behavior:'smooth'})}}><Icon size={18}/>{reportDefinitions[key].title}</button>})}</div></>}</article></div>}
  </div>;
}

function ReportSide({title,action,empty,children}:{title:string;action:string;empty:string;children:any}){return <article className="admin-report-side-card-v2"><header><h2>{title}</h2><button>{action} →</button></header>{children?.length?children:<p>{empty}</p>}</article>}
function periodLabel(period:Period){return ({today:'Сегодня','7':'7 дней','30':'30 дней',month:'этот месяц',previousMonth:'прошлый месяц',custom:'свой период'})[period]}
function buildRows(type:ReportType, orders:AdminOrder[], products:CatalogProduct[], reviews:AdminReview[], coupons:AdminCoupon[], usages:CouponUsage[], productMap:Map<string,CatalogProduct>, range:{start:Date;end:Date}) {
  const orderRow=(order:AdminOrder)=>({id:order.id,date:rawDate(order.created_at),order:`#${order.id}`,customer:order.customer?.name||'Гость',phone:order.customer?.phone||'—',email:order.customer?.email||'—',items:(order.items||[]).map((item)=>item.title||productMap.get(item.slug||'')?.title||'Товар').join(', '),quantity:(order.items||[]).reduce((sum,item)=>sum+Number(item.quantity||1),0),amount:money((order.items||[]).reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||1),0)),discount:'0 BYN',delivery:order.delivery||'Не указан',total:money(order.total),status:order.status||'Новый',payment:order.payment_method||'Не указан',manager:order.manager||'Не назначен',source:order.source||'Сайт'});
  if(type==='sales'||type==='orders') return orders.map(orderRow);
  if(type==='products'){const map=new Map<string,any>();orders.filter((order)=>paidStatuses.has(order.status||'')).forEach((order)=>(order.items||[]).forEach((item)=>{const slug=item.slug||item.title||'unknown';const existing=map.get(slug)||{id:slug,title:item.title||productMap.get(slug)?.title||'Товар',sku:item.sku||'—',category:productMap.get(slug)?.category||'Без категории',sold:0,orders:new Set(),revenue:0,lastSale:order.created_at};existing.sold+=Number(item.quantity||1);existing.orders.add(order.id);existing.revenue+=Number(item.price||0)*Number(item.quantity||1);if(new Date(order.created_at||0)>new Date(existing.lastSale||0))existing.lastSale=order.created_at;map.set(slug,existing)}));return Array.from(map.values()).map((item)=>({...item,orders:item.orders.size,revenue:money(item.revenue),average:money(item.sold?item.revenue/item.sold:0),lastSale:rawDate(item.lastSale)}));}
  if(type==='categories'){const map=new Map<string,any>();orders.filter((order)=>paidStatuses.has(order.status||'')).forEach((order)=>(order.items||[]).forEach((item)=>{const name=productMap.get(item.slug||'')?.category||'Без категории';const existing=map.get(name)||{id:name,category:name,sold:0,orders:new Set(),revenue:0};existing.sold+=Number(item.quantity||1);existing.orders.add(order.id);existing.revenue+=Number(item.price||0)*Number(item.quantity||1);map.set(name,existing)}));const total=Array.from(map.values()).reduce((sum,item)=>sum+item.revenue,0);return Array.from(map.values()).map((item)=>({...item,orders:item.orders.size,revenue:money(item.revenue),average:money(item.orders.size?item.revenue/item.orders.size:0),share:`${total?Math.round(item.revenue/total*100):0}%`}));}
  if(type==='customers'){const map=new Map<string,any>();orders.forEach((order)=>{const key=order.customer?.phone||order.customer?.email||order.customer?.name||order.id;const existing=map.get(key)||{id:key,name:order.customer?.name||'Гость',phone:order.customer?.phone||'—',email:order.customer?.email||'—',orders:0,total:0,first:order.created_at,last:order.created_at};existing.orders++;existing.total+=Number(order.total||0);if(new Date(order.created_at||0)<new Date(existing.first||0))existing.first=order.created_at;if(new Date(order.created_at||0)>new Date(existing.last||0))existing.last=order.created_at;map.set(key,existing)});return Array.from(map.values()).map((item)=>({...item,total:money(item.total),average:money(item.orders?item.total/item.orders:0),first:rawDate(item.first),last:rawDate(item.last),status:item.orders>2?'Постоянный':'Активный'}));}
  if(type==='coupons'){const couponMap=new Map(coupons.map((coupon)=>[coupon.id,coupon]));return usages.filter((usage)=>dateInRange(usage.created_at,range)).reduce((rows:any[],usage)=>{const coupon=couponMap.get(usage.coupon_id);const found=rows.find((row)=>row.id===usage.coupon_id);if(found){found.uses++;found.customers.add(usage.customer_key||usage.customer_name||usage.id);found.amount+=Number(usage.order_total||0);found.discount+=Number(usage.discount_amount||0)}else rows.push({id:usage.coupon_id,name:coupon?.name||'Купон',code:coupon?.code||'—',uses:1,customers:new Set([usage.customer_key||usage.customer_name||usage.id]),amount:Number(usage.order_total||0),discount:Number(usage.discount_amount||0),period:`${rawDate(coupon?.starts_at||undefined)} — ${rawDate(coupon?.ends_at||undefined)}`});return rows},[]).map((item)=>({...item,customers:item.customers.size,amount:money(item.amount),discount:money(item.discount),average:money(item.uses?item.discount/item.uses:0)}));}
  if(type==='delivery'){const map=new Map<string,any>();orders.forEach((order)=>{const key=order.delivery||'Не указан';const row=map.get(key)||{id:key,delivery:key,orders:0,amount:0};row.orders++;row.amount+=Number(order.total||0);map.set(key,row)});return Array.from(map.values()).map((item)=>({...item,amount:money(item.amount),average:money(item.orders?item.amount/item.orders:0),cost:'По тарифу',share:`${orders.length?Math.round(item.orders/orders.length*100):0}%`}));}
  if(type==='payment')return orders.map((order)=>({id:order.id,order:`#${order.id}`,customer:order.customer?.name||'Гость',payment:order.payment_method||'Не указан',status:paidStatuses.has(order.status||'')?'Оплачен':order.status||'Новый',amount:money(order.total),date:paidStatuses.has(order.status||'')?rawDate(order.created_at):'—'}));
  if(type==='reviews')return reviews.filter((review)=>dateInRange(review.created_at,range)).map((review)=>({id:review.id,date:rawDate(review.created_at),customer:review.user_name||review.user_email||'Покупатель',product:productMap.get(review.product_slug)?.title||review.product_slug||'—',rating:`${review.rating} ★`,text:review.comment,status:review.status,photos:review.photo_urls?.length?'Да':'Нет',source:review.source||'Сайт'}));
  return [{id:'sales',section:'Продажи',title:'Заказов',value:orders.length},{id:'revenue',section:'Продажи',title:'Выручка (учитываемые статусы)',value:money(orders.filter((order)=>paidStatuses.has(order.status||'')).reduce((sum,order)=>sum+Number(order.total||0),0))},{id:'products',section:'Товары',title:'В каталоге',value:products.length},{id:'reviews',section:'Отзывы',title:'За период',value:reviews.filter((review)=>dateInRange(review.created_at,range)).length}];
}
