'use client';
import { useMemo, useState } from 'react';
import { Download, FileJson, FileSpreadsheet, PackageCheck, ShoppingBag, UsersRound } from 'lucide-react';
import type { AdminOrder, AdminRequest } from '@/lib/adminCommerce';
import { money } from '@/lib/adminCommerce';

type Overview = { products: number; orders: number; requests: number; pages: number };
const downloads = [{ label: 'Полная резервная копия', detail: 'JSON: все данные CMS', href: '/api/admin/export?type=all&format=json', icon: FileJson }, { label: 'Каталог товаров', detail: 'CSV для Excel и импорта', href: '/api/admin/export?type=products&format=csv', icon: PackageCheck }, { label: 'Заказы', detail: 'CSV для менеджера или бухгалтера', href: '/api/admin/export?type=orders&format=csv', icon: ShoppingBag }, { label: 'Клиенты', detail: 'CSV с профилями покупателей', href: '/api/admin/export?type=users&format=csv', icon: UsersRound }];
export function AdminReportsClient({ overview, orders, requests }: { overview: Overview; orders: AdminOrder[]; requests: AdminRequest[] }) {
  const [period, setPeriod] = useState<'7' | '30' | 'all'>('30'); const since = useMemo(() => period === 'all' ? 0 : Date.now() - Number(period) * 86400000, [period]); const reportOrders = orders.filter((order) => !since || new Date(order.created_at || 0).getTime() >= since); const reportRequests = requests.filter((request) => !since || new Date(request.created_at || 0).getTime() >= since); const paid = reportOrders.filter((order) => /оплачен|выполнен|передан/i.test(order.status || '')).reduce((sum, order) => sum + Number(order.total || 0), 0); const potential = reportOrders.reduce((sum, order) => sum + Number(order.total || 0), 0); const statusRows = Object.entries(reportOrders.reduce<Record<string, number>>((result, order) => { const key = order.status || 'Новый'; result[key] = (result[key] || 0) + 1; return result; }, {}));
  return <div className="admin-reports-cms"><section className="admin-page-head"><div><p>Аналитика</p><h1>Отчёты и выгрузки</h1><span>Рабочая сводка по заказам и заявкам. Выберите период, проверьте цифры и скачайте нужные данные.</span></div><label className="admin-report-period">Период<select value={period} onChange={(event) => setPeriod(event.target.value as typeof period)}><option value="7">7 дней</option><option value="30">30 дней</option><option value="all">За всё время</option></select></label></section><section className="admin-report-metrics"><article><b>{reportOrders.length}</b><span>заказов за период</span></article><article><b>{reportRequests.length}</b><span>заявок за период</span></article><article><b>{money(potential)} BYN</b><span>сумма всех заказов</span></article><article><b>{money(paid)} BYN</b><span>оплачено / выполнено</span></article></section><section className="admin-reports-grid"><article className="admin-reports-card"><header><h2>Статусы заказов</h2><span>Количество в выбранном периоде</span></header>{statusRows.length ? <div className="admin-report-statuses">{statusRows.map(([status, count]) => <div key={status}><span>{status}</span><b>{count}</b><i style={{ width: `${Math.max(8, count / Math.max(1, reportOrders.length) * 100)}%` }} /></div>)}</div> : <p className="admin-report-empty">За выбранный период заказов нет.</p>}</article><article className="admin-reports-card"><header><h2>Состояние CMS</h2><span>Содержимое, доступное в системе</span></header><div className="admin-report-inventory"><span>Товары <b>{overview.products}</b></span><span>Страницы <b>{overview.pages}</b></span><span>Все заказы <b>{overview.orders}</b></span><span>Все заявки <b>{overview.requests}</b></span></div></article></section><section className="admin-reports-downloads"><header><div><h2>Выгрузки</h2><span>Файлы формируются из актуальных данных.</span></div><a href="/admin/backup">Управление резервными копиями</a></header><div>{downloads.map(({ label, detail, href, icon: Icon }) => <a key={href} href={href} target="_blank"><Icon size={22} /><span><b>{label}</b><small>{detail}</small></span><Download size={18} /></a>)}</div></section></div>;
}
