'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Eye, EyeOff, Plus, Save, Trash2 } from 'lucide-react';
import { AdminImagePicker } from '@/components/AdminImagePicker';
import type { ServiceCard, ServicesControlSettings, ServiceStep } from '@/lib/servicesControl';

function Field({ label, value, change, area = false }: { label: string; value: string; change: (value: string) => void; area?: boolean }) { return <label className="admin-production-field"><span>{label}</span>{area ? <textarea rows={3} value={value} onChange={(event) => change(event.target.value)} /> : <input value={value} onChange={(event) => change(event.target.value)} />}</label>; }
function patchItem<T extends { id: string }>(items: T[], id: string, patch: Partial<T>) { return items.map((item) => item.id === id ? { ...item, ...patch } : item); }
function id(prefix: string) { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`; }

export function AdminServicesClient({ initialSettings }: { initialSettings: ServicesControlSettings }) {
  const [settings, setSettings] = useState(initialSettings); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const patchHero = (patch: Partial<ServicesControlSettings['hero']>) => setSettings((current) => ({ ...current, hero: { ...current.hero, ...patch } }));
  async function save() { setSaving(true); setMessage(''); try { const response = await fetch('/api/admin/services-control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Не удалось сохранить услуги.'); setSettings(data.settings || settings); setMessage('Услуги сохранены и будут показаны на публичной странице согласно видимости направлений.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Ошибка сохранения.'); } finally { setSaving(false); } }
  function addService() { const item: ServiceCard = { id: id('service'), directionKey: 'custom_service', icon: 'tools', title: 'Новая услуга', subtitle: 'Опишите услугу для клиента.', image: '/assets/service-metal.jpg', items: ['Первое преимущество', 'Второе преимущество'], href: '/contacts', visible: false, order: settings.services.length + 1 }; setSettings((current) => ({ ...current, services: [...current.services, item] })); }
  function addStep() { const item: ServiceStep = { id: id('step'), number: String(settings.steps.length + 1).padStart(2, '0'), title: 'Новый этап', text: 'Опишите этап работы.', visible: false, order: settings.steps.length + 1 }; setSettings((current) => ({ ...current, steps: [...current.steps, item] })); }
  return <div className="admin-production-editor"><section className="admin-production-hero"><div><p>Контент сайта</p><h1>Услуги</h1><span>Управляйте публичной страницей услуг: первый экран, карточки, преимущества, этапы и примеры задач.</span></div><div><Link href="/services" target="_blank">Открыть страницу ↗</Link><button type="button" onClick={save} disabled={saving}><Save size={17} />{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></section>{message && <p className="admin-production-message">{message}</p>}
    <section className="admin-production-card"><header><div><h2>Первый экран услуг</h2><span>Основное сообщение и изображение.</span></div><button type="button" className={settings.hero.enabled ? 'admin-production-toggle is-on' : 'admin-production-toggle'} onClick={() => patchHero({ enabled: !settings.hero.enabled })}>{settings.hero.enabled ? <Eye size={16} /> : <EyeOff size={16} />}{settings.hero.enabled ? 'Опубликовано' : 'Скрыто'}</button></header><div className="admin-production-grid"><Field label="Надзаголовок" value={settings.hero.kicker} change={(kicker) => patchHero({ kicker })} /><Field label="Заголовок" value={settings.hero.title} change={(title) => patchHero({ title })} /><Field label="Текст" value={settings.hero.text} change={(text) => patchHero({ text })} area /><AdminImagePicker label="Фото" value={settings.hero.image} onChange={(image) => patchHero({ image })} /><Field label="Основная кнопка" value={settings.hero.primaryLabel} change={(primaryLabel) => patchHero({ primaryLabel })} /><Field label="Вторая кнопка" value={settings.hero.secondaryLabel} change={(secondaryLabel) => patchHero({ secondaryLabel })} /></div></section>
    <section className="admin-production-card"><header><div><h2>Карточки услуг</h2><span>Карточка отображается, когда включена здесь и соответствующее направление доступно в настройках сайта.</span></div><button type="button" onClick={addService}><Plus size={16} />Добавить услугу</button></header><div className="admin-production-results">{settings.services.map((item) => <article key={item.id}><div className="admin-production-item-actions"><button type="button" className={item.visible ? 'admin-production-toggle is-on' : 'admin-production-toggle'} onClick={() => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { visible: !item.visible }) }))}>{item.visible ? <Eye size={16} /> : <EyeOff size={16} />}</button><button type="button" className="admin-production-delete" onClick={() => setSettings((current) => ({ ...current, services: current.services.filter((value) => value.id !== item.id) }))}><Trash2 size={16} /></button></div><Field label="Название" value={item.title} change={(title) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { title }) }))} /><Field label="Ключ направления" value={item.directionKey} change={(directionKey) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { directionKey }) }))} /><Field label="Описание" value={item.subtitle} change={(subtitle) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { subtitle }) }))} area /><AdminImagePicker label="Фото услуги" value={item.image} onChange={(image) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { image }) }))} /><Field label="Ссылка" value={item.href} change={(href) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { href }) }))} /><Field label="Пункты через |" value={item.items.join(' | ')} change={(value) => setSettings((current) => ({ ...current, services: patchItem(current.services, item.id, { items: value.split('|').map((part) => part.trim()).filter(Boolean) }) }))} /></article>)}</div></section>
    <section className="admin-production-card"><header><div><h2>Как проходит работа</h2><span>Этапы оказываются на странице услуг в указанном порядке.</span></div><button type="button" onClick={addStep}><Plus size={16} />Добавить этап</button></header><div className="admin-production-steps">{settings.steps.map((item) => <article key={item.id}><div className="admin-production-item-actions"><button type="button" className={item.visible ? 'admin-production-toggle is-on' : 'admin-production-toggle'} onClick={() => setSettings((current) => ({ ...current, steps: patchItem(current.steps, item.id, { visible: !item.visible }) }))}>{item.visible ? <Eye size={16} /> : <EyeOff size={16} />}</button><button type="button" className="admin-production-delete" onClick={() => setSettings((current) => ({ ...current, steps: current.steps.filter((value) => value.id !== item.id) }))}><Trash2 size={16} /></button></div><Field label="Номер" value={item.number} change={(number) => setSettings((current) => ({ ...current, steps: patchItem(current.steps, item.id, { number }) }))} /><Field label="Название" value={item.title} change={(title) => setSettings((current) => ({ ...current, steps: patchItem(current.steps, item.id, { title }) }))} /><Field label="Описание" value={item.text} change={(text) => setSettings((current) => ({ ...current, steps: patchItem(current.steps, item.id, { text }) }))} area /></article>)}</div></section>
    <section className="admin-production-card"><header><div><h2>Примеры задач</h2><span>Короткие теги под блоком услуг.</span></div></header><Field label="Примеры через |" value={settings.examples.join(' | ')} change={(value) => setSettings((current) => ({ ...current, examples: value.split('|').map((part) => part.trim()).filter(Boolean) }))} /></section>
  </div>;
}
