'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { AlertCircle, ArrowDownRight, ArrowUpRight, CalendarDays, ChartNoAxesCombined, ChevronRight, CircleDollarSign, Download, Package, ShoppingCart, Star, Tag, Truck, Users } from 'lucide-react';
import type { StatsCompare, StatsPeriod } from '@/lib/adminStats';

type Stats = any;
const money = (value: number) => new Intl.NumberFormat('ru-RU').format(Number(value || 0));
const labels: Record<StatsPeriod, string> = { today:'Сегодня', '7':'7 дней', '30':'30 дней', '90':'90 дней', year:'Год', custom:'Свой период' };
const statusColors: Record<string, string> = { 'Новый':'#3b82f6', 'В работе':'#f97316', 'Ожидает оплаты':'#a855f7', 'Оплачен':'#22a06b', 'Передан в доставку':'#06b6d4', 'Выполнен':'#16a34a', 'Отменён':'#ef4444' };

function Delta({ value }: { value: number | null }) { if (value === null) return <em className="stats-delta-v1 neutral">Новый показатель</em>; return <em className={`stats-delta-v1 ${value >= 0 ? 'up' : 'down'}`}>{value >= 0 ? <ArrowUpRight size={13}/> : <ArrowDownRight size={13}/>} {Math.abs(value)}%</em>; }
function Empty({ text }: { text: string }) { return <p className="stats-empty-v1">{text}</p>; }

export function AdminStatsClient({ initialStats }: { initialStats: Stats }) {
  const [period, setPeriod] = useState<StatsPeriod>('30'); const [compare, setCompare] = useState<StatsCompare>('previous'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [stats, setStats] = useState<Stats>(initialStats); const [loading, setLoading] = useState(false); const [metric, setMetric] = useState<'revenue'|'orders'|'averageOrder'>('revenue'); const [error, setError] = useState('');
  const params = useMemo(() => { const query = new URLSearchParams({ period, compare }); if (period === 'custom' && from) query.set('from', from); if (period === 'custom' && to) query.set('to', to); return query.toString(); }, [period, compare, from, to]);
  useEffect(() => { if (period === 'custom' && (!from || !to)) return; let live = true; setLoading(true); setError(''); fetch(`/api/admin/stats?${params}`, { cache: 'no-store' }).then(async (response) => { const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.message || 'Не удалось загрузить статистику.'); if (live) setStats(data.stats); }).catch((reason) => live && setError(reason.message || 'Не удалось загрузить статистику.')).finally(() => live && setLoading(false)); return () => { live = false; }; }, [params, period, from, to]);
  const series = stats.salesSeries || []; const maximum = Math.max(1, ...series.map((item: any) => Number(item[metric] || 0))); const orderTotal = (stats.statuses || []).reduce((sum: number, item: any) => sum + item.count, 0);
  function exportJson() { const blob = new Blob([JSON.stringify(stats, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `bullmet-stats-${stats.range?.from || 'period'}.json`; link.click(); URL.revokeObjectURL(url); }
  const kpis = [
    { key:'revenue', label:'Выручка', icon: CircleDollarSign, href:'/admin/orders', format: (v:number) => `${money(v)} BYN` },
    { key:'orders', label:'Заказы', icon: ShoppingCart, href:'/admin/orders', format: (v:number) => money(v) },
    { key:'averageOrder', label:'Средний чек', icon: ChartNoAxesCombined, href:'/admin/orders', format: (v:number) => v ? `${money(v)} BYN` : '—' },
    { key:'customers', label:'Покупатели', icon: Users, href:'/admin/customers', format: (v:number) => money(v) },
    { key:'itemsSold', label:'Товаров продано', icon: Package, href:'/admin/products?sort=sales_desc', format: (v:number) => money(v) }
  ];
  return <div className="admin-stats-v1">
    <header className="admin-stats-head-v1"><div><h1>Статистика</h1><p>Аналитика продаж, заказов, товаров и покупателей Bullmet.</p></div><button onClick={exportJson}><Download size={16}/>Экспорт отчёта</button></header>
    <section className="admin-stats-period-v1"><div>{(Object.keys(labels) as StatsPeriod[]).map((item) => <button key={item} className={period === item ? 'active' : ''} onClick={() => setPeriod(item)}>{item === 'custom' && <CalendarDays size={15}/>} {labels[item]}</button>)}</div><label>Сравнивать с:<select value={compare} onChange={(event) => setCompare(event.target.value as StatsCompare)}><option value="previous">Предыдущим периодом</option><option value="year">Прошлым годом</option><option value="none">Без сравнения</option></select></label>{period === 'custom' && <aside><input type="date" value={from} onChange={(event) => setFrom(event.target.value)}/><span>—</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)}/></aside>}</section>
    {error && <div className="admin-stats-error-v1">{error}<button onClick={() => window.location.reload()}>Повторить</button></div>}
    {loading && <div className="admin-stats-loading-v1">Обновляем данные за выбранный период…</div>}
    <section className="admin-stats-kpis-v1">{kpis.map(({key,label,icon: Icon,href,format}) => <Link href={href} key={key}><span><Icon size={21}/></span><small>{label}</small><b>{format(Number(stats.kpis?.[key]?.value || 0))}</b><Delta value={stats.kpis?.[key]?.change ?? null}/><i>{stats.kpis?.[key]?.previous !== undefined ? `${format(Number(stats.kpis[key].previous || 0))} за период сравнения` : '—'}</i></Link>)}</section>
    <section className="admin-stats-main-grid-v1"><article className="admin-stats-card-v1 admin-stats-chart-card-v1"><header><div><h2>Динамика продаж</h2><span>{stats.range?.label}</span></div><select value={metric} onChange={(event) => setMetric(event.target.value as typeof metric)}><option value="revenue">Выручка</option><option value="orders">Заказы</option><option value="averageOrder">Средний чек</option></select></header>{series.some((item:any) => item[metric]) ? <div className="admin-stats-chart-v1">{series.map((item:any) => <div key={item.date} title={`${item.label}: ${metric === 'revenue' || metric === 'averageOrder' ? `${money(item[metric])} BYN` : item[metric]}`}><i style={{ height:`${Math.max(4, Number(item[metric] || 0) / maximum * 100)}%` }}/><span>{item.label}</span></div>)}</div> : <Empty text="За выбранный период данных для графика нет."/>}</article>
      <article className="admin-stats-card-v1"><header><div><h2>Статусы заказов</h2><span>Распределение за период</span></div><Link href="/admin/orders">Подробнее <ChevronRight size={15}/></Link></header>{orderTotal ? <div className="admin-statuses-v1"><div className="admin-donut-v1" style={{ background: `conic-gradient(${(stats.statuses || []).map((item:any, index:number) => `${statusColors[item.status] || '#94a3b8'} ${((stats.statuses || []).slice(0,index).reduce((sum:number,row:any)=>sum+row.count,0) / orderTotal * 100)}% ${((stats.statuses || []).slice(0,index+1).reduce((sum:number,row:any)=>sum+row.count,0) / orderTotal * 100)}%`).join(',')})` }}><b>{orderTotal}</b><span>заказов</span></div><div>{(stats.statuses || []).map((item:any) => <Link href={`/admin/orders?status=${encodeURIComponent(item.status)}`} key={item.status}><i style={{background:statusColors[item.status] || '#94a3b8'}}/><span>{item.status}</span><b>{item.count}</b><small>{Math.round(item.count / orderTotal * 100)}%</small></Link>)}</div></div> : <Empty text="За выбранный период заказов нет."/>}</article></section>
    <section className="admin-stats-triple-v1"><ListCard title="Топ товаров" href="/admin/products?sort=sales_desc" icon={<Package size={18}/>} empty="Продаж пока нет.">{(stats.topProducts || []).map((item:any,index:number) => <Link href={`/admin/products?search=${encodeURIComponent(item.slug)}`} key={item.slug}><b>{index+1}</b>{item.image ? <img src={item.image} alt=""/> : <span/>}<strong>{item.title}</strong><em>{item.sold} шт.</em><i>{money(item.revenue)} BYN</i></Link>)}</ListCard><ListCard title="Категории" href="/admin/categories" icon={<Tag size={18}/>} empty="Продаж по категориям нет.">{(stats.categories || []).map((item:any) => <Link href={`/admin/products?category=${encodeURIComponent(item.name)}`} key={item.name}><strong>{item.name}</strong><em>{item.orders} заказов</em><i>{money(item.revenue)} BYN</i><small><b style={{width:`${item.share}%`}}/></small><mark>{item.share}%</mark></Link>)}</ListCard><article className="admin-stats-card-v1 admin-customers-card-v1"><header><div><h2>Покупатели</h2><span>За выбранный период</span></div><Users size={18}/></header><div><p><span>Новые</span><b>{stats.customers?.newCustomers || 0}</b></p><p><span>Повторные</span><b>{stats.customers?.repeatCustomers || 0}</b></p><p><span>Постоянные</span><b>{stats.customers?.loyalCustomers || 0}</b></p></div><aside><Users size={18}/><span>Повторные покупки</span><b>{stats.customers?.repeatRate || 0}%</b><small>доля покупателей с предыдущими заказами</small></aside></article></section>
    <section className="admin-stats-triple-v1"><ListCard title="Доставка" href="/admin/delivery" icon={<Truck size={18}/>} empty="Способ получения пока не указан.">{(stats.delivery || []).map((item:any) => <Link href={`/admin/orders?delivery=${encodeURIComponent(item.name)}`} key={item.name}><strong>{item.name}</strong><em>{item.count} заказов</em><small><b style={{width:`${item.share}%`}}/></small><mark>{item.share}%</mark></Link>)}</ListCard><ListCard title="Оплата" href="/admin/orders" icon={<CircleDollarSign size={18}/>} empty="Оплаченных заказов нет.">{(stats.payment || []).map((item:any) => <Link href={`/admin/orders?payment=${encodeURIComponent(item.name)}`} key={item.name}><strong>{item.name}</strong><em>{item.count} заказов</em><i>{money(item.amount)} BYN</i><mark>{item.share}%</mark></Link>)}</ListCard><article className="admin-stats-card-v1 admin-coupons-card-v1"><header><div><h2>Купоны и скидки</h2><span>За выбранный период</span></div><Link href="/admin/coupons">К купонам <ChevronRight size={15}/></Link></header><p>Использовано купонов <b>{stats.coupons?.used || 0}</b></p><p>Сумма скидок <b>{money(stats.coupons?.totalDiscount || 0)} BYN</b></p><p>Средняя скидка <b>{money(stats.coupons?.averageDiscount || 0)} BYN</b></p>{stats.coupons?.top?.length ? <aside>{stats.coupons.top.map((item:any)=><span key={item.code}>{item.code}<b>{item.count}</b></span>)}</aside> : null}</article></section>
    <section className="admin-stats-bottom-v1"><article className="admin-stats-card-v1 admin-review-stats-v1"><header><div><h2>Отзывы</h2><span>Только опубликованные</span></div><Link href="/admin/reviews">Все отзывы <ChevronRight size={15}/></Link></header>{stats.reviews?.total ? <div><aside><b>{stats.reviews.average}</b><span>★★★★★</span><small>{stats.reviews.total} отзывов</small></aside><section>{stats.reviews.distribution.map((item:any) => <p key={item.rating}><span>{item.rating} ★</span><i><b style={{width:`${stats.reviews.total ? item.count / stats.reviews.total * 100 : 0}%`}}/></i><em>{item.count}</em></p>)}</section></div> : <Empty text="За выбранный период опубликованных отзывов нет."/>}</article><article className="admin-stats-card-v1 admin-insights-v1"><header><div><h2>На что обратить внимание</h2><span>Сигналы по реальным данным</span></div><AlertCircle size={19}/></header>{(stats.insights || []).map((item:any) => <Link href={item.href} key={item.title} className={item.type}><i /><span>{item.title}</span><ChevronRight size={16}/></Link>)}</article></section>
  </div>;
}

function ListCard({ title, href, icon, empty, children }: { title:string; href:string; icon:ReactNode; empty:string; children:ReactNode }) { const hasChildren = Array.isArray(children) ? children.length > 0 : Boolean(children); return <article className="admin-stats-card-v1 admin-stats-list-v1"><header><div><h2>{title}</h2></div><Link href={href}>Все <ChevronRight size={15}/></Link></header><div className="admin-stats-list-icon-v1">{icon}</div>{hasChildren ? <section>{children}</section> : <Empty text={empty}/>}</article>; }
