import { NextRequest, NextResponse } from 'next/server';
import { couponCode } from '@/lib/adminCoupons';
import { serverSupabase } from '@/lib/serverSupabase';

export const dynamic = 'force-dynamic';
function list(value: unknown) { return Array.isArray(value) ? value.map(String).filter(Boolean) : []; }
function patchOf(body: any) { const patch: Record<string, unknown> = {}; ['name','description','starts_at','ends_at'].forEach((key)=> { if (key in body) patch[key]=body[key] || null; }); if ('code' in body) patch.code=couponCode(body.code); if ('type' in body && ['percentage','fixed','free_shipping'].includes(body.type)) patch.type=body.type; if ('status' in body && ['active','inactive','archived'].includes(body.status)) patch.status=body.status; ['value','max_discount','total_usage_limit','usage_limit_per_customer','minimum_order_amount'].forEach((key)=>{ if(key in body) patch[key]=body[key] === '' || body[key] === null ? null : Math.max(0,Number(body[key])); }); ['first_order_only','new_customers_only','allow_discounted_products'].forEach((key)=>{if(key in body)patch[key]=Boolean(body[key]);}); if('category_ids' in body)patch.category_ids=list(body.category_ids); if('product_ids' in body)patch.product_ids=list(body.product_ids); return patch; }
export async function GET(_: NextRequest,{params}:{params:{id:string}}) { if (!serverSupabase) return NextResponse.json({ok:false,message:'Supabase не подключён.'},{status:500}); const [coupon, usages] = await Promise.all([serverSupabase.from('coupons').select('*').eq('id',params.id).maybeSingle(),serverSupabase.from('coupon_usages').select('*').eq('coupon_id',params.id).order('created_at',{ascending:false})]); if(!coupon.data)return NextResponse.json({ok:false,message:'Купон не найден.'},{status:404}); return NextResponse.json({ok:true,coupon:coupon.data,usages:usages.data||[]}); }
export async function PATCH(request:NextRequest,{params}:{params:{id:string}}) { if(!serverSupabase)return NextResponse.json({ok:false,message:'Supabase не подключён.'},{status:500}); const patch=patchOf(await request.json().catch(()=>({}))); if(!Object.keys(patch).length)return NextResponse.json({ok:false,message:'Нет изменений.'},{status:400}); const {data,error}=await serverSupabase.from('coupons').update(patch).eq('id',params.id).select('*').single(); if(error)return NextResponse.json({ok:false,message:error.code==='23505'?'Этот промокод уже существует.':error.message},{status:409}); await serverSupabase.from('admin_activity_log').insert({action:'coupon_update',entity:'coupons',entity_id:params.id,payload:patch}).then(()=>null); return NextResponse.json({ok:true,coupon:data}); }
export async function DELETE(_:NextRequest,{params}:{params:{id:string}}) { if(!serverSupabase)return NextResponse.json({ok:false,message:'Supabase не подключён.'},{status:500}); const {count,error:countError}=await serverSupabase.from('coupon_usages').select('id',{count:'exact',head:true}).eq('coupon_id',params.id); if(countError)return NextResponse.json({ok:false,message:countError.message},{status:500}); if(count)return NextResponse.json({ok:false,message:'Использованный купон нельзя удалить — переместите его в архив.'},{status:409}); const {error}=await serverSupabase.from('coupons').delete().eq('id',params.id); if(error)return NextResponse.json({ok:false,message:error.message},{status:500}); return NextResponse.json({ok:true}); }
